@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Sat May 09 15:59:58 +0800 2026
REM SW Build 2552052 on Fri May 24 14:49:42 MDT 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
echo "xsim tb_segmented_256bit_butterfly_1_behav -key {Behavioral:sim_1:Functional:tb_segmented_256bit_butterfly_1} -tclbatch tb_segmented_256bit_butterfly_1.tcl -protoinst "protoinst_files/design_1.protoinst" -view F:/experiment/python/trae/ntt_axi/NTT-accelerator-for-ZKP-0.4/ntt_3_tfdg_full_twiddle_4_2_sum_axi_5/ntt_1/tb_montgomery_top_behav.wcfg -view F:/experiment/python/trae/ntt_axi/NTT-accelerator-for-ZKP-0.4/ntt_3_tfdg_full_twiddle_4_2_sum_axi_5/ntt_1/mod_exp_tb_behav.wcfg -view F:/experiment/python/trae/ntt_axi/NTT-accelerator-for-ZKP-0.4/ntt_3_tfdg_full_twiddle_4_2_sum_axi_5/ntt_1/tb_ntt_parallel_recurrence_unit_behav.wcfg -view F:/experiment/python/trae/ntt_axi/NTT-accelerator-for-ZKP-0.4/ntt_3_tfdg_full_twiddle_4_2_sum_axi_5/ntt_1/tb_ntt_accelerator_behav.wcfg -view F:/experiment/python/trae/ntt_axi/NTT-accelerator-for-ZKP-0.4/ntt_3_tfdg_full_twiddle_4_2_sum_axi_5/ntt_1/tb_ntt_accelerator_behav1.wcfg -view F:/experiment/python/trae/ntt_axi/NTT-accelerator-for-ZKP-0.4/ntt_3_tfdg_full_twiddle_4_2_sum_axi_5/ntt_1/tb_ntt_accelerator_behav2.wcfg -view F:/experiment/python/trae/ntt_axi/NTT-accelerator-for-ZKP-0.4/ntt_3_tfdg_full_twiddle_4_2_sum_axi_5/ntt_1/tb_ntt_axi_behav.wcfg -log simulate.log"
call xsim  tb_segmented_256bit_butterfly_1_behav -key {Behavioral:sim_1:Functional:tb_segmented_256bit_butterfly_1} -tclbatch tb_segmented_256bit_butterfly_1.tcl -protoinst "protoinst_files/design_1.protoinst" -view F:/experiment/python/trae/ntt_axi/NTT-accelerator-for-ZKP-0.4/ntt_3_tfdg_full_twiddle_4_2_sum_axi_5/ntt_1/tb_montgomery_top_behav.wcfg -view F:/experiment/python/trae/ntt_axi/NTT-accelerator-for-ZKP-0.4/ntt_3_tfdg_full_twiddle_4_2_sum_axi_5/ntt_1/mod_exp_tb_behav.wcfg -view F:/experiment/python/trae/ntt_axi/NTT-accelerator-for-ZKP-0.4/ntt_3_tfdg_full_twiddle_4_2_sum_axi_5/ntt_1/tb_ntt_parallel_recurrence_unit_behav.wcfg -view F:/experiment/python/trae/ntt_axi/NTT-accelerator-for-ZKP-0.4/ntt_3_tfdg_full_twiddle_4_2_sum_axi_5/ntt_1/tb_ntt_accelerator_behav.wcfg -view F:/experiment/python/trae/ntt_axi/NTT-accelerator-for-ZKP-0.4/ntt_3_tfdg_full_twiddle_4_2_sum_axi_5/ntt_1/tb_ntt_accelerator_behav1.wcfg -view F:/experiment/python/trae/ntt_axi/NTT-accelerator-for-ZKP-0.4/ntt_3_tfdg_full_twiddle_4_2_sum_axi_5/ntt_1/tb_ntt_accelerator_behav2.wcfg -view F:/experiment/python/trae/ntt_axi/NTT-accelerator-for-ZKP-0.4/ntt_3_tfdg_full_twiddle_4_2_sum_axi_5/ntt_1/tb_ntt_axi_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
